// Generated by https://quicktype.io

export interface HeroCardItem {
  id: string;
  superhero: string;
  publisher: HeroCardPublisher;
  alter_ego: string;
  first_appearance: string;
  characters: string;
  alt_img?: string;
}

export enum HeroCardPublisher {
  DCComics = "DC Comics",
  MarvelComics = "Marvel Comics",
}